language: php

php:
  - 5.6
  - 7.0
  - hhvm

before_script:
  - cp .env.travis .env
  - mysql -e 'create database inventory_manager;'
  - composer self-update
  - composer install --no-interaction

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

install: travis_retry composer install --no-interaction --prefer-source

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml

after_success:
  - travis_retry php vendor/bin/coveralls
  # or enable logging
  - travis_retry php vendor/bin/coveralls -v
